name: unittest-on-push
on: push

jobs:
  build:
    name: Unit test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with: 
          toolchain: stable
      - run: cargo test
      - run: cargo build --release
            
